import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "vitest";

test("dnd5e templates reuse the shared partials", () => {
  const detailsTemplate = readFileSync(new URL("../templates/details.hbs", import.meta.url), "utf8");
  const inventoryTemplate = readFileSync(new URL("../templates/inventory.hbs", import.meta.url), "utf8");
  const biographyTemplate = readFileSync(new URL("../templates/biography.hbs", import.meta.url), "utf8");
  const dnd5eFavoritesGroupTemplate = readFileSync(new URL("../templates/partials/favorites-group.hbs", import.meta.url), "utf8");
  const spellsTemplate = readFileSync(new URL("../templates/spells.hbs", import.meta.url), "utf8");
  const featuresTemplate = readFileSync(new URL("../templates/features.hbs", import.meta.url), "utf8");
  const effectsTemplate = readFileSync(new URL("../templates/effects.hbs", import.meta.url), "utf8");
  const featureRowTemplate = readFileSync(new URL("../templates/partials/feature-row.hbs", import.meta.url), "utf8");
  const spellRowTemplate = readFileSync(new URL("../templates/partials/spell-row.hbs", import.meta.url), "utf8");
  const inventoryRowTemplate = readFileSync(new URL("../templates/partials/inventory-list-row.hbs", import.meta.url), "utf8");
  const skillRowTemplate = readFileSync(new URL("../templates/partials/details-skill-row.hbs", import.meta.url), "utf8");
  const toolRowTemplate = readFileSync(new URL("../templates/partials/details-tool-row.hbs", import.meta.url), "utf8");
  const effectRowTemplate = readFileSync(new URL("../templates/partials/effect-row.hbs", import.meta.url), "utf8");
  const dnd5eHeaderDialogsTemplate = readFileSync(new URL("../templates/partials/header-details-dialogs.hbs", import.meta.url), "utf8");
  assert.match(dnd5eHeaderDialogsTemplate, /partials\/number-adjust-dialog\.hbs/);
  assert.match(detailsTemplate, /partials\/pane-unavailable\.hbs/);
  assert.match(inventoryTemplate, /partials\/pane-unavailable\.hbs/);
  assert.match(biographyTemplate, /partials\/pane-unavailable\.hbs/);
  assert.match(spellsTemplate, /partials\/pane-search-toolbar\.hbs/);
  assert.match(featuresTemplate, /partials\/pane-search-toolbar\.hbs/);
  assert.match(effectsTemplate, /partials\/pane-search-toolbar\.hbs/);
  assert.doesNotMatch(featureRowTemplate, /partials\/number-adjust-dialog\.hbs/);
  assert.match(featureRowTemplate, /partials\/expandable-detail-row\.hbs/);
  assert.match(featureRowTemplate, /partials\/favorite-context-menu\.hbs/);
  assert.match(spellRowTemplate, /partials\/number-adjust-dialog\.hbs/);
  assert.match(spellRowTemplate, /partials\/expandable-detail-row\.hbs/);
  assert.match(spellRowTemplate, /partials\/favorite-context-menu\.hbs/);
  assert.match(inventoryRowTemplate, /partials\/number-adjust-dialog\.hbs/);
  assert.match(inventoryRowTemplate, /partials\/expandable-detail-row\.hbs/);
  assert.match(inventoryRowTemplate, /partials\/favorite-context-menu\.hbs/);
  assert.match(skillRowTemplate, /partials\/favorite-context-menu\.hbs/);
  assert.match(toolRowTemplate, /partials\/favorite-context-menu\.hbs/);
  assert.match(effectRowTemplate, /partials\/expandable-detail-row\.hbs/);
  assert.match(effectRowTemplate, /partials\/favorite-context-menu\.hbs/);
  assert.match(dnd5eFavoritesGroupTemplate, /partials\/details-skill-row\.hbs/);
  assert.match(dnd5eFavoritesGroupTemplate, /partials\/details-tool-row\.hbs/);
  assert.match(dnd5eFavoritesGroupTemplate, /partials\/inventory-list-row\.hbs/);
  assert.match(dnd5eFavoritesGroupTemplate, /partials\/spell-row\.hbs/);
  assert.match(dnd5eFavoritesGroupTemplate, /partials\/feature-row\.hbs/);
  assert.match(dnd5eFavoritesGroupTemplate, /partials\/effect-row\.hbs/);
});
