import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "vitest";

test("journal templates preserve required regions and separate phone navigation levels", () => {
  const shellTemplate = readFileSync(new URL("../src/templates/shell.hbs", import.meta.url), "utf8");
  const journalTemplate = readFileSync(new URL("../src/templates/journal.hbs", import.meta.url), "utf8");
  const entryTemplate = readFileSync(new URL("../src/templates/journal-entry.hbs", import.meta.url), "utf8");
  const pageTemplate = readFileSync(new URL("../src/templates/journal-page.hbs", import.meta.url), "utf8");
  const contentListRowTemplate = readFileSync(new URL("../src/templates/partials/content-list-row.hbs", import.meta.url), "utf8");
  const css = readFileSync(new URL("../src/styles/pocket-foundry.css", import.meta.url), "utf8");
  const moduleSource = readFileSync(new URL("../src/module.ts", import.meta.url), "utf8");
  const shellSource = readFileSync(new URL("../src/core/mobile-shell/controller.ts", import.meta.url), "utf8");
  const shellHelperSource = readFileSync(new URL("../src/core/mobile-shell/controller-helpers-shell.ts", import.meta.url), "utf8");
  const searchHelperSource = readFileSync(new URL("../src/core/mobile-shell/controller-helpers-search.ts", import.meta.url), "utf8");
  const journalActionSource = readFileSync(new URL("../src/core/mobile-shell/actions-journal.ts", import.meta.url), "utf8");
  const reactiveRefreshSource = readFileSync(new URL("../src/services/reactive-refresh.ts", import.meta.url), "utf8");

  assert.match(shellTemplate, /templates\/journal\.hbs/);
  assert.match(shellTemplate, /templates\/journal-entry\.hbs/);
  assert.match(shellTemplate, /templates\/journal-page\.hbs/);
  assert.match(shellTemplate, /data-action="journal-up"/);
  assert.match(shellTemplate, /aria-label="Up one Journal level"/);
  assert.match(journalTemplate, /class="content pf-view journal-browser"/);
  assert.match(journalTemplate, /class="section content-group pf-view-section journal-entry-list"/);
  assert.match(journalTemplate, /class="section-heading content-group-heading pf-view-section-heading journal-entry-list-heading"/);
  assert.match(journalTemplate, /class="content-table content-list pf-view-list journal-list"/);
  assert.match(journalTemplate, /class="content-list-head journal-list-head"/);
  assert.match(journalTemplate, /partials\/content-list-row\.hbs/);
  assert.match(contentListRowTemplate, /class="row content-list-row/);
  assert.match(contentListRowTemplate, /class="item-icon"/);
  assert.match(contentListRowTemplate, /class="row-title content-row-title"/);
  assert.match(contentListRowTemplate, /class="row-action content-list-action"/);
  assert.match(entryTemplate, /class="content pf-view journal-entry-view"/);
  assert.match(entryTemplate, /class="section content-group pf-view-section journal-page-list"/);
  assert.match(entryTemplate, /class="section-heading content-group-heading pf-view-section-heading journal-page-list-heading"/);
  assert.match(entryTemplate, /class="content-table content-list pf-view-list journal-list"/);
  assert.match(entryTemplate, /class="content-list-head journal-list-head"/);
  assert.match(entryTemplate, /class="row content-list-row journal-page-row/);
  assert.match(entryTemplate, /data-action="journal-create-page"/);
  assert.match(entryTemplate, /data-action="journal-delete-page"/);
  assert.match(entryTemplate, /fa-trash/);
  assert.match(pageTemplate, /class="content pf-view journal-page-view"/);
  assert.match(pageTemplate, /class="section-heading content-group-heading pf-view-section-heading journal-page-title-row"/);
  assert.match(pageTemplate, /data-action="journal-edit-page"/);
  assert.match(pageTemplate, /class="section pf-view-section reader journal-reader"/);
  assert.match(pageTemplate, /data-journal-links/);
  assert.match(pageTemplate, /journal-image-frame/);
  assert.match(pageTemplate, /journal-pdf-frame/);
  assert.match(pageTemplate, /journal-video-frame/);
  assert.match(moduleSource, /`\$\{TEMPLATE_ROOT\}\/journal\.hbs`/);
  assert.match(moduleSource, /`\$\{TEMPLATE_ROOT\}\/journal-entry\.hbs`/);
  assert.match(moduleSource, /`\$\{TEMPLATE_ROOT\}\/journal-page\.hbs`/);
  assert.match(shellHelperSource, /createMobileJournalService/);
  assert.match(shellHelperSource, /buildJournalShellViewModel/);
  assert.match(journalActionSource, /target\.dataset\.action === "journal-open-entry"/);
  assert.match(journalActionSource, /target\.dataset\.action === "journal-open-page"/);
  assert.match(journalActionSource, /target\.dataset\.action === "journal-create-page"/);
  assert.match(journalActionSource, /target\.dataset\.action === "journal-delete-page"/);
  assert.match(journalActionSource, /target\.dataset\.action === "journal-edit-page"/);
  assert.match(journalActionSource, /target\.dataset\.action === "journal-up"/);
  assert.match(journalActionSource, /getJournalParentRoute/);
  assert.match(searchHelperSource, /\.journal-reader a\[data-uuid\]/);
  assert.match(shellSource, /createReactiveRefreshController/);
  assert.match(reactiveRefreshSource, /createJournalEntryPage/);
  assert.match(reactiveRefreshSource, /updateJournalEntryPage/);
  assert.match(reactiveRefreshSource, /deleteJournalEntryPage/);
  assert.match(css, /\.pocket-foundry-root \.journal-browser/);
  assert.match(css, /\.pocket-foundry-root \.journal-entry-view/);
  assert.match(css, /\.pocket-foundry-root \.journal-page-view/);
  assert.match(css, /\.pocket-foundry-root \.journal-reader/);
  assert.match(css, /\.journal-reader \{ @apply[^}]*p-2\.5/);
  assert.match(css, /\.journal-text-content h1/);
  assert.match(css, /\.pocket-foundry-root \.content-group/);
  assert.match(css, /\.pocket-foundry-root \.content-list\.content-table/);
  assert.match(css, /\.pocket-foundry-root \.content-list-row/);
  assert.match(css, /\.pocket-foundry-root \.pf-view/);
  assert.match(css, /\.pocket-foundry-root \.pf-view-section/);
  assert.match(css, /\.pocket-foundry-root \.pf-view-list\.content-list\.content-table/);
  assert.doesNotMatch(journalTemplate + entryTemplate, /sheet-group|sheet-list|sheet-table|sheet-row-title|sheet-list-value/);
  assert.doesNotMatch(journalTemplate + entryTemplate, /data-swipe-ignore|{{#if selected}}active{{\/if}}/);
  assert.doesNotMatch(css, /\.journal-page-row\.active/);
  assert.doesNotMatch(journalTemplate, /data-action="create"|data-action="delete"|data-action="edit"|Open Sheet|textarea|<input/);
  assert.doesNotMatch(entryTemplate + pageTemplate, /data-action="create"|data-action="delete"|data-action="edit"|Open Sheet|textarea|<input/);
});

