/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 *
 * This file is generated by scripts/build.ts via generateCharacterSheetAdapterManifest().
 * Manual edits will be overwritten on the next build.
 */
import type { CharacterSheetAdapter } from "./character-sheet-adapter.ts";
import { characterSheetAdapter as adapter_dnd5e } from "./dnd5e/index.ts";

export const BUILT_IN_CHARACTER_SHEET_ADAPTERS: ReadonlyArray<{ systemId: string; adapter: CharacterSheetAdapter }> = [
  { systemId: "dnd5e", adapter: adapter_dnd5e }
];
