import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const addonRoot = resolve(projectRoot, "src");
const tempRoot = resolve(projectRoot, ".build");
const distRoot = resolve(projectRoot, "dist");
const staticEntries = [
  "module.json",
  "templates",
  "systems"
];

if (process.argv.includes("--clean")) {
  clean();
  process.exit(0);
}

const moduleId = getModuleId(resolve(addonRoot, "module.json"));
const tempModule = resolve(tempRoot, moduleId);
const finalRoot = resolve(projectRoot, "dist", moduleId);
const tscPath = resolve(projectRoot, "node_modules/typescript/bin/tsc");
const tailwindCliPath = resolve(projectRoot, "node_modules/@tailwindcss/cli/dist/index.mjs");

assertDependency("typescript", tscPath);
assertDependency("esbuild", resolve(projectRoot, "node_modules/esbuild"));
assertDependency("@tailwindcss/cli", tailwindCliPath);

generateCharacterSheetAdapterManifest();
runTypeCheck();
stageOutput();
await bundleModule();
copyStaticFiles();
mergeLanguageFiles();
compileStyles();
publishOutput();

function clean(): void {
  rmSync(distRoot, { recursive: true, force: true });
  rmSync(tempRoot, { recursive: true, force: true });
}

function runTypeCheck(): void {
  execFileSync(process.execPath, [tscPath, "--noEmit"], {
    cwd: projectRoot,
    stdio: "inherit"
  });
}

function stageOutput(): void {
  rmSync(tempRoot, { recursive: true, force: true });
  mkdirSync(resolve(tempModule, "scripts"), { recursive: true });
}

async function bundleModule(): Promise<void> {
  const { build } = await import("esbuild");
  await build({
    entryPoints: [resolve(addonRoot, "module.ts")],
    outfile: resolve(tempModule, "scripts/pocket-foundry.js"),
    bundle: true,
    format: "esm",
    target: "es2022",
    minify: true
  });
}

function generateCharacterSheetAdapterManifest(): void {
  const systemsRoot = resolve(projectRoot, "src", "systems");
  const generatedPath = resolve(systemsRoot, "character-sheet-adapters.generated.ts");
  const entries = existsSync(systemsRoot)
    ? readdirSync(systemsRoot, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => name !== "_generated")
      .sort()
    : [];

  const imports: string[] = [];
  const registrations: string[] = [];

  for (const systemId of entries) {
    const indexPath = resolve(systemsRoot, systemId, "index.ts");
    if (!existsSync(indexPath)) continue;
    const adapterImportId = `adapter_${systemId.replace(/[^a-z0-9_]/gi, "_")}`;
    imports.push(`import { characterSheetAdapter as ${adapterImportId} } from "./${systemId}/index.ts";`);
    registrations.push(`{ systemId: "${systemId}", adapter: ${adapterImportId} }`);
  }

  const payload = `/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 *
 * This file is generated by scripts/build.ts via generateCharacterSheetAdapterManifest().
 * Manual edits will be overwritten on the next build.
 */
import type { CharacterSheetAdapter } from "./character-sheet-adapter.ts";
${imports.join("\n")}

export const BUILT_IN_CHARACTER_SHEET_ADAPTERS: ReadonlyArray<{ systemId: string; adapter: CharacterSheetAdapter }> = [
  ${registrations.join(",\n  ")}
];
`;

  writeFileSync(generatedPath, payload, "utf8");
}

/**
 * Copies static module assets into the temporary build tree.
 */
function copyStaticFiles(): void {
  for (const entry of staticEntries) {
    const source = resolve(addonRoot, entry);
    if (!existsSync(source)) throw new Error(`Required module asset is missing: ${entry}`);
    cpSync(source, resolve(tempModule, entry), { recursive: true, filter: shouldCopyStaticAsset });
  }
}

/**
 * Excludes source language folders from raw static copying because they are
 * merged into Foundry's module-level language directory separately.
 */
function shouldCopyStaticAsset(sourcePath: string): boolean {
  const relativePath = relative(addonRoot, sourcePath);
  return !relativePath.split(/[\\/]/).includes("lang");
}

/**
 * Merges core and system-owned language JSON files into Foundry module language
 * files keyed by locale.
 */
function mergeLanguageFiles(): void {
  const languageSources = collectLanguageSources();
  const outputRoot = resolve(tempModule, "lang");
  mkdirSync(outputRoot, { recursive: true });

  for (const [lang, files] of [...languageSources.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    const merged: Record<string, unknown> = {};
    for (const file of files.sort()) {
      Object.assign(merged, JSON.parse(readFileSync(file, "utf8")) as Record<string, unknown>);
    }
    writeFileSync(resolve(outputRoot, `${lang}.json`), `${JSON.stringify(merged, null, 2)}\n`, "utf8");
  }
}

/**
 * Collects every source language JSON file grouped by locale name.
 */
function collectLanguageSources(): Map<string, string[]> {
  const sources = new Map<string, string[]>();
  for (const file of collectJsonFiles(resolve(addonRoot, "lang"))) addLanguageSource(sources, file);
  for (const file of collectJsonFiles(resolve(addonRoot, "systems"))) {
    if (file.split(/[\\/]/).includes("lang")) addLanguageSource(sources, file);
  }
  if (sources.size === 0) throw new Error("No language source files found.");
  return sources;
}

/**
 * Adds one language JSON path to the grouped locale source map.
 */
function addLanguageSource(sources: Map<string, string[]>, file: string): void {
  const lang = basename(file, ".json");
  sources.set(lang, [...(sources.get(lang) ?? []), file]);
}

/**
 * Recursively lists JSON files below a root directory when it exists.
 */
function collectJsonFiles(root: string): string[] {
  if (!existsSync(root)) return [];
  const files: string[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const entryPath = join(root, entry.name);
    if (entry.isDirectory()) files.push(...collectJsonFiles(entryPath));
    else if (entry.isFile() && entry.name.toLowerCase().endsWith(".json")) files.push(entryPath);
  }
  return files;
}

function publishOutput(): void {
  removeWithRetry(finalRoot);
  mkdirSync(distRoot, { recursive: true });
  copyWithRetry(tempModule, finalRoot);
  removeWithRetry(tempRoot);
}

function compileStyles(): void {
  const styleInputs = [
    resolve(addonRoot, "styles/pocket-foundry.css"),
    ...collectSystemStyleInputs()
  ];

  for (const inputPath of styleInputs) {
    const outputPath = resolve(tempModule, relative(addonRoot, inputPath));
    mkdirSync(dirname(outputPath), { recursive: true });
    execFileSync(process.execPath, [
      tailwindCliPath,
      "-i",
      inputPath,
      "-o",
      outputPath,
      "--minify"
    ], {
      cwd: projectRoot,
      stdio: "inherit"
    });
  }
}

function collectSystemStyleInputs(): string[] {
  const systemsRoot = resolve(addonRoot, "systems");
  if (!existsSync(systemsRoot)) return [];

  const styleInputs: string[] = [];
  const systemEntries = readdirSync(systemsRoot, { withFileTypes: true }).filter(entry => entry.isDirectory());

  for (const systemEntry of systemEntries) {
    const stylesRoot = resolve(systemsRoot, systemEntry.name, "styles");
    if (!existsSync(stylesRoot)) continue;

    for (const file of readdirSync(stylesRoot, { withFileTypes: true })) {
      if (!file.isFile()) continue;
      if (!file.name.toLowerCase().endsWith(".css")) continue;
      styleInputs.push(resolve(stylesRoot, file.name));
    }
  }

  return styleInputs.sort();
}

function assertDependency(name: string, binPath: string): void {
  if (existsSync(binPath)) return;

  throw new Error(`Build dependency "${name}" is missing. Run npm install from the workspace root, then run npm run build.`);
}

function removeWithRetry(path: string): void {
  retryFileOperation(() => rmSync(path, { recursive: true, force: true }), `remove ${path}`);
}

function copyWithRetry(source: string, destination: string): void {
  retryFileOperation(() => cpSync(source, destination, { recursive: true }), `copy ${source} to ${destination}`);
}

function retryFileOperation(operation: () => void, label: string): void {
  let lastError: unknown;

  for (let attempt = 1; attempt <= 10; attempt += 1) {
    try {
      operation();
      return;
    } catch (error) {
      lastError = error;
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 100 * attempt);
    }
  }

  throw new Error(`Could not ${label} after retries. Last error: ${String(lastError)}`);
}

function getModuleId(moduleManifestPath: string): string {
  if (!existsSync(moduleManifestPath)) {
    throw new Error(`Missing module manifest: ${moduleManifestPath}`);
  }

  const moduleManifest = JSON.parse(readFileSync(moduleManifestPath, "utf8")) as { id?: unknown };
  if (typeof moduleManifest.id !== "string" || moduleManifest.id.length === 0) {
    throw new Error(`module.json is missing a valid "id": ${moduleManifestPath}`);
  }

  return moduleManifest.id;
}

