import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const addonRoot = resolve(projectRoot, "src");
const tempRoot = resolve(projectRoot, ".build");
const moduleId = "pocket-foundry";
const tempModule = resolve(tempRoot, moduleId);
const finalRoot = resolve(projectRoot, "dist", moduleId);
const distRoot = resolve(projectRoot, "dist");
const staticEntries = [
  "module.json",
  "templates",
  "systems"
];

if (process.argv.includes("--clean")) {
  clean();
  process.exit(0);
}

const tscPath = resolve(projectRoot, "node_modules/typescript/bin/tsc");
const tailwindCliPath = resolve(projectRoot, "node_modules/@tailwindcss/cli/dist/index.mjs");

assertDependency("typescript", tscPath);
assertDependency("esbuild", resolve(projectRoot, "node_modules/esbuild"));
assertDependency("@tailwindcss/cli", tailwindCliPath);

generateCharacterSheetAdapterManifest();
runTypeCheck();
stageOutput();
await bundleModule();
copyStaticFiles();
compileStyles();
publishOutput();

function clean(): void {
  rmSync(finalRoot, { recursive: true, force: true });
  rmSync(tempRoot, { recursive: true, force: true });
}

function runTypeCheck(): void {
  execFileSync(process.execPath, [tscPath, "--noEmit"], {
    cwd: projectRoot,
    stdio: "inherit"
  });
}

function stageOutput(): void {
  rmSync(tempRoot, { recursive: true, force: true });
  mkdirSync(resolve(tempModule, "scripts"), { recursive: true });
}

async function bundleModule(): Promise<void> {
  const { build } = await import("esbuild");
  await build({
    entryPoints: [resolve(addonRoot, "module.ts")],
    outfile: resolve(tempModule, "scripts/pocket-foundry.js"),
    bundle: true,
    format: "esm",
    target: "es2022",
    minify: true
  });
}

function generateCharacterSheetAdapterManifest(): void {
  const systemsRoot = resolve(projectRoot, "src", "systems");
  const generatedPath = resolve(systemsRoot, "character-sheet-adapters.generated.ts");
  const entries = existsSync(systemsRoot)
    ? readdirSync(systemsRoot, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => name !== "_generated")
      .sort()
    : [];

  const imports: string[] = [];
  const registrations: string[] = [];

  for (const systemId of entries) {
    const indexPath = resolve(systemsRoot, systemId, "index.ts");
    if (!existsSync(indexPath)) continue;
    const adapterImportId = `adapter_${systemId.replace(/[^a-z0-9_]/gi, "_")}`;
    imports.push(`import { characterSheetAdapter as ${adapterImportId} } from "./${systemId}/index.ts";`);
    registrations.push(`{ systemId: "${systemId}", adapter: ${adapterImportId} }`);
  }

  const payload = `/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 *
 * This file is generated by scripts/build.ts via generateCharacterSheetAdapterManifest().
 * Manual edits will be overwritten on the next build.
 */
import type { CharacterSheetAdapter } from "./character-sheet-adapter.ts";
${imports.join("\n")}

export const BUILT_IN_CHARACTER_SHEET_ADAPTERS: ReadonlyArray<{ systemId: string; adapter: CharacterSheetAdapter }> = [
  ${registrations.join(",\n  ")}
];
`;

  writeFileSync(generatedPath, payload, "utf8");
}

function copyStaticFiles(): void {
  for (const entry of staticEntries) {
    const source = resolve(addonRoot, entry);
    if (!existsSync(source)) throw new Error(`Required module asset is missing: ${entry}`);
    cpSync(source, resolve(tempModule, entry), { recursive: true });
  }
}

function publishOutput(): void {
  removeWithRetry(finalRoot);
  mkdirSync(distRoot, { recursive: true });
  copyWithRetry(tempModule, finalRoot);
  removeWithRetry(tempRoot);
}

function compileStyles(): void {
  const styleInputs = [
    resolve(addonRoot, "styles/pocket-foundry.css"),
    ...collectSystemStyleInputs()
  ];

  for (const inputPath of styleInputs) {
    const outputPath = resolve(tempModule, relative(addonRoot, inputPath));
    mkdirSync(dirname(outputPath), { recursive: true });
    execFileSync(process.execPath, [
      tailwindCliPath,
      "-i",
      inputPath,
      "-o",
      outputPath,
      "--minify"
    ], {
      cwd: projectRoot,
      stdio: "inherit"
    });
  }
}

function collectSystemStyleInputs(): string[] {
  const systemsRoot = resolve(addonRoot, "systems");
  if (!existsSync(systemsRoot)) return [];

  const styleInputs: string[] = [];
  const systemEntries = readdirSync(systemsRoot, { withFileTypes: true }).filter(entry => entry.isDirectory());

  for (const systemEntry of systemEntries) {
    const stylesRoot = resolve(systemsRoot, systemEntry.name, "styles");
    if (!existsSync(stylesRoot)) continue;

    for (const file of readdirSync(stylesRoot, { withFileTypes: true })) {
      if (!file.isFile()) continue;
      if (!file.name.toLowerCase().endsWith(".css")) continue;
      styleInputs.push(resolve(stylesRoot, file.name));
    }
  }

  return styleInputs.sort();
}

function assertDependency(name: string, binPath: string): void {
  if (existsSync(binPath)) return;

  throw new Error(`Build dependency "${name}" is missing. Run npm install from the workspace root, then run npm run build.`);
}

function removeWithRetry(path: string): void {
  retryFileOperation(() => rmSync(path, { recursive: true, force: true }), `remove ${path}`);
}

function copyWithRetry(source: string, destination: string): void {
  retryFileOperation(() => cpSync(source, destination, { recursive: true }), `copy ${source} to ${destination}`);
}

function retryFileOperation(operation: () => void, label: string): void {
  let lastError: unknown;

  for (let attempt = 1; attempt <= 10; attempt += 1) {
    try {
      operation();
      return;
    } catch (error) {
      lastError = error;
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 100 * attempt);
    }
  }

  throw new Error(`Could not ${label} after retries. Last error: ${String(lastError)}`);
}

